"""add_foto_to_material

Revision ID: 1ad0d7c0f66f
Revises: 04551aaa1683
Create Date: 2026-06-26 12:18:14.099502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad0d7c0f66f'
down_revision: Union[str, Sequence[str], None] = '04551aaa1683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiales', sa.Column('foto', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materiales', 'foto')
    # ### end Alembic commands ###
